config/routes.rb
Rails.application.routes.draw do

  root 'books#index'
  devise_for :users
  resources :books
  resources :users do
    resources :bookmarks, only: [:index, :create, :destroy]
  end

  resources :genres
  resources :likes, only: [:create, :destroy]


  post 'like/:id', to: 'books#like', as: 'like_book'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :image_url, presence: true, unless: -> { image_url.present? }
  validates :genre_id, presence: true
  validates :title, presence: true
  validates :author, presence: true
  belongs_to :genre
  has_many :likes
  has_many :bookmarks
  has_many :users, through: :bookmarks
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :user_id, uniqueness:  { scope: :book_id }
  belongs_to :user
  belongs_to :book
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :books
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness:  { scope: :book_id }
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord

  has_many :bookmarks
  has_many :books, through: :bookmarks
  has_many :likes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @books = current_user.books
  end



  def create
    @bookmark = current_user.bookmarks.new(bookmark_params)
    if !@bookmark.save
      flash[:notice] = @bookmark.errors.full_messages.to_sentence
    end
    redirect_to root_path
  end

  def destroy
    @bookmark = current_user.bookmarks.find(params[:id])
    @bookmark.destroy
    redirect_to root_path
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:book_id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :set_genres

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    @book.image_url = "https://bookclub.ua/img/supersize/200_219/standart.png" if @book.image_url.blank?

    respond_to do |format|
      if @book.save
        format.html { redirect_to root_path, notice: "Book was successfully created." }
      else
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    redirect_to root_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author, :publication_year, :genre_id, :image_url)
  end

  def set_genres
    @genres = Genre.all.order(:name)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[ show edit update destroy ]

  # GET /genres or /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1 or /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to genre_url(@genre), notice: "Genre was successfully created." }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to genre_url(@genre), notice: "Genre was successfully updated." }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url, notice: "Genre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_genre
    @genre = Genre.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(like_params)
    if !@like.save
      flash[:notice] = @like.errors.full_messages.to_sentence
    end
    redirect_to root_path
  end
  def destroy
    @like = current_user.likes.find(params[:id])
    # book = @like.book
    @like.destroy
    redirect_to root_path
  end

  private

  def like_params
    params.require(:like).permit(:book_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/bookmarks/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10">
      <h1>Your Bookmarks</h1>
      <div class="row row-cols-auto">
        <%= render 'books/book' %>
      </div>
    </div>
    <div class="col-sm-2">
      <div class='d-flex justify-content-end'>
        <%= render 'layouts/sidebar' %>
      </div>
    </div>
  </div>
</div>

app/views/books/_book.html.erb
<% @books.each do |book| %>
  <div class="col">
    <div class="card mb-3" style="width: 18rem ">
      <div class="card-body">
        <div class="row">
          <div class="col-9">
            <h4 class="card-title"> <strong><%= book.title %></strong></h4>
          </div>
          <div class="col">
            <div class="text-end">
              <% if current_user%>
                <% bookmark = current_user.bookmarks.find_by(book: book) %>
                <% if bookmark.nil? %>
                  <%= button_to "", user_bookmarks_path(user_id: current_user.id), params: { bookmark: { book_id: book.id }}, method: :post, class: "fa-regular fa-bookmark btn btn-outline-warning mb-3 text-dark" %>
                <% else %>
                  <%= button_to "", user_bookmark_path(user_id: current_user.id, id: bookmark.id), method: :delete, class: "fa-solid fa-bookmark btn btn-outline-warning mb-3 text-dark" %>
                <% end %>
              <% else %>
              <% end %>
            </div>
          </div>
        </div>
        <hr>
        <div class="center-block" style="height: 370px;">
          <img class="w-100" src="<%= book.image_url %>" alt="...">
        </div>
        <hr>
        <p>Author: <%= book.author %></p>
        <p>Publication year: <%= book.publication_year %></p>
        <h6 class="card-subtitle mb-2 text-body-secondary" style="max-width: 200px;"></h6>

        <% if current_user%>
          <% if current_user.admin%>
            <p class="card-text">Genre: <%= link_to book.genre.name, book.genre %></p>
          <% else %>
            <p class="card-text">Genre: <%= link_to book.genre.name %></p>
          <% end %>
        <% else %>
          <p class="card-text">Genre: <%= link_to book.genre.name%></p>
        <% end %>

        <div class="row">
          <div class="col">
            <%=  book.likes.count %> Likes
          </div>
          <div class="col">
            <div class="d-flex justify-content-center"></div>
            <div class="text-end">
              <% if current_user%>
                <% like = current_user.likes.find_by(book: book) %>
                <% if like.nil? %>
                  <%= button_to "", likes_path, params: { like: { book_id: book.id }}, method: :post, class: "fa-regular fa-thumbs-up btn btn-outline-success mb-3 text-dark" %>
                <% else %>
                  <%= button_to "", like_path(like), method: :delete, class: "fa-regular fa-thumbs-down btn btn-outline-danger mb-3 text-dark" %>
                <% end %>
              <% else %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="text-center">
          <% if current_user%>
            <% if current_user.admin%>
              <%= link_to "Edit this book", edit_book_path(book), class: "btn btn-outline-secondary mb-3" %>
              <%= button_to "Destroy this book", book, method: :delete, class: "btn btn-outline-secondary mb-3" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/books/_form.html.erb
<%= form_with model: @book do |f| %>

  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= f.label :title, class: 'form-label' %>
    <%= f.text_field :title, required: true, class: 'form-control'%>
  </div>
  <div class="mb-3">
    <%= f.label :author, class: 'form-label' %>
    <%= f.text_field :author, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :genre_id, class: 'form-label' %>
    <%= collection_select(:book, :genre_id, Genre.all, :id, :name, {}, { :multiple => false, :class => 'form-control' }) %>
  </div>
  <div class="mb-3">
    <%= f.label :publication_year, class: 'form-label' %>
    <%= f.text_field :publication_year, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :image_url, class: 'form-label' %>
    <%= f.text_field :image_url, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= button_to "Accept", books_path, method: :get, class: "btn btn-outline-secondary mb-3" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10">
      <h1>Home page with Books</h1>
      <div class="row row-cols-auto">
        <%= render 'books/book' %>
      </div>
    </div>
    <div class="col-sm-2">
      <div class='d-flex justify-content-end'>
        <%= render 'layouts/sidebar' %>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="row">
  <div class="col-7">
    <h1>New book</h1>
    <%= render "form", book: @book %>
    <div>
      <%= link_to "Back to books", books_path, class: "btn btn-small btn-outline-secondary my-2" %>
    </div>
  </div>
  <div class="col-4">
    <h1>Add new genre</h1>
    <%= render 'genres/form', genre: Genre.new %>
  </div>
</div>

app/views/books/show.html.erb
<!--<div class="container-fluid text-center">-->
  <%# if current_user%>
    <%#= link_to "Edit this book", edit_book_path(@book), class: "btn btn-outline-secondary mb-3" %>
    <%#= button_to "Destroy this book", @book, method: :delete, class: "btn btn-outline-secondary mb-3" %>
  <%# end %>
  <%#= link_to "Back to books", books_path, class: "btn btn-outline-secondary mb-3" %>
<!--</div>-->

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |f| %>
  <% if genre.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name, style: "display: block" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div>
    <%= f.submit 'Accept', class: "btn btn-outline-secondary mb-3"%>
  </div>
<% end %>

app/views/genres/_genre.html.erb
<div id="<%= dom_id genre %>">
  <p>
    <strong>Name:</strong>


<!--  <div>-->
    <%# current_user.bookmarks.each do |bookmark| %>
      <%#= button_to bookmark.book.title, bookmark.book, class: "btn btn-outline-secondary mb-3" %>
    <%# end %>
<!--  </div>-->
  </p>



<!--  <div id="genres">-->
    <%# @genres.each do |genre| %>
      <%#= render genre %>
<!--      <p>-->
        <%#= link_to "Show this genre", genre %>
<!--      </p>-->

</div>

<!--<div>-->
  <%# current_user.bookmarks.each do |bookmark| %>
    <%#= render bookmark %>
  <%# end %>
<!--</div>-->

app/views/genres/edit.html.erb
<h1>Editing genre</h1>

<%= render "form", genre: @genre %>

<br>

<div>
  <%= link_to "Show this genre", @genre %> |
  <%= link_to "Back to genres", genres_path %>
</div>

app/views/genres/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Genres</h1>

<%= link_to "New genre", new_genre_path, class: "btn btn-outline-secondary mb-3" %>

<!--<div id="genres">-->
  <%# @genres.each do |genre| %>
    <%#= render genre %>
<!--    <p>-->
      <%#= link_to "Show this genre", genre %>
<!--    </p>-->
  <%# end %>
<!--</div>-->

<%#= link_to "New genre", new_genre_path %>


<div class="row row-cols-auto">

  <% @genres.each do |genre| %>
    <div class="col">
      <div class="card mb-3" style="width: 18rem">
        <div class="card-body">


          <%# if current_user%>
            <%# bookmark = current_user.bookmarks.find_by(genre: genre) %>
            <%# if bookmark.nil? %>
              <%#= button_to "Bookmark", bookmarks_path, params: { bookmark: { book_id: genre.id }}, method: :post, class: "btn btn-outline-secondary mb-3" %>
            <%# else %>
              <%#= button_to "Unbookmark", bookmark_path(bookmark), method: :delete, class: "btn btn-outline-secondary mb-3" %>
            <%# end %>
          <%# else %>
          <%# end %>


          <h5 class="card-title"> <strong><%= genre.name %></strong></h5>

          <h6 class="card-subtitle mb-2 text-body-secondary" style="max-width: 200px;"></h6>


          <%# if current_user%>
<!--            <p class="card-text">Genre: <%#= link_to "Show this genre", genre.name, genre.genre %></p>-->
          <%# else %>
<!--            <p class="card-text"><%#= link_to "Edit genre", genre.name %></p>-->
          <%# end %>
          <div class="row">

<%#= link_to "Show this genre", genre %>

<!--            <div class="d-flex justify-content-end"></div>-->
            <%# if current_user%>
              <%# like = current_user.likes.find_by(book: book) %>
              <%# if like.nil? %>
                <%#= button_to "Like", likes_path, params: { like: { book_id: book.id }}, method: :post, class: "btn btn-outline-secondary mb-3" %>
              <%# else %>
                <%#= button_to "Unlike", like_path(like), method: :delete, class: "btn btn-outline-secondary mb-3" %>
              <%# end %>
            <%# else %>
            <%# end %>


            <%# if current_user%>
              <%#= link_to "Edit this book", edit_book_path(book), class: "btn btn-outline-secondary mb-3" %>
              <%#= button_to "Destroy this book", book, method: :delete, class: "btn btn-outline-secondary mb-3" %>
            <%# end %>


          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "Back to books", '/books', class: "btn btn-outline-secondary mb-3" %>






<!--<div>-->
  <%# current_user.bookmarks.each do |bookmark| %>
    <%#= button_to bookmark.book.title, bookmark.book, class: "btn btn-outline-secondary mb-3" %>
  <%# end %>
<!--</div>-->

app/views/genres/new.html.erb
<h1>New genre</h1>

<%= render "form", genre: @genre %>

<br>

<div>
  <%= link_to "Back to genres", genres_path %>
</div>

app/views/genres/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @genre %>

<div>
  <%= link_to "Edit this genre", edit_genre_path(@genre) %> |
  <%= link_to "Back to genres", genres_path %>

  <%= button_to "Destroy this genre", @genre, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Main page</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="https://bookclub.ua/">Books</a>
        </li>
      </ul>
      <ul class="navbar-nav">
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
  <span class="fs-2 text-center">Online Library panel</span>
  <hr>
  <% if current_user%>
    <div class="align-self-end text-end mx-3">
      <span class="fs-3 text-center">User options</span>
      <ul class="nav nav-pills flex-column mb-auto">
        <li>
          <%= link_to "Bookmarks", user_bookmarks_path(current_user), class: "btn btn-small btn-outline-secondary my-2" %>
        </li>
      </ul>
    </div>
    <% if current_user.admin%>
      <div class="align-self-end text-end mx-3">
        <span class="fs-3 text-center">Admin options</span>
        <ul class="nav nav-pills flex-column mb-auto">
          <li class="nav-item">
            <%= link_to "Create new Book", new_book_path, class: "btn btn-small btn-outline-secondary my-2" %>
          </li>
          <li>
            <%= link_to "Genres", genres_path, class: "btn btn-small btn-outline-secondary my-2" %>
          </li>
        </ul>
      </div>
    <% end %>
  <% else %>
    <div class="container-fluid">
      <div class="d-flex align-content-center text-center">
        <p>Please Login for More functionality</p>
      </div>
    </div>
  <% end %>
<hr>
<div class="container-fluid ">
  <ul class="nav-pills ">
    <% if current_user%>
      <div class="fs-5">
        <%= current_user.email %>
      </div>
      <div class="row">
        <div class="container text-center">
          <%= link_to "Edit Account", edit_user_registration_path, class: "btn btn-small btn-outline-secondary my-2" %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-outline-danger my-2" %>
        </div>
      </div>
    <% else %>
      <div class="row">
        <div class="container text-center">
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-small btn-outline-primary my-2" %>
          <%= link_to "Sign In", new_user_session_path, class: "btn btn-small btn-outline-success my-2" %>
        </div>
      </div>
    <% end %>
  </ul>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online Library</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js"></script>


  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>



<body>
  <%= render 'layouts/navbar' %>
  <%= yield %>
</body>

</html>